apiVersion: v1
kind: Template
metadata:
  name: flask-app-build
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      build: ${APP_NAME}
    name: ${APP_NAME}
    namespace: ${IMAGE_NAMESPACE}
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: ${GIT_BRANCH}
        uri: ${GIT_REPOSITORY_URL}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.7
          namespace: ${IMAGE_NAMESPACE}
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: Generic
    - type: ConfigChange
    - type: ImageChange
  status:
    lastVersion: 10
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      build: ${APP_NAME}
    name: ${APP_NAME}
    namespace: ${IMAGE_NAMESPACE}

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      build: ${APP_NAME}
    name: python
    namespace: ${IMAGE_NAMESPACE}
  spec:
    lookupPolicy:
      local: false
    tags:
      - annotations:
          openshift.io/imported-from: 'python:3.7'
        from:
          kind: DockerImage
          name: 'python:3.7'
        name: '3.7'
        referencePolicy:
          type: Source
parameters:
- name: APP_NAME
  description: The name of the application
  value: pdfmagic
  required: true
- name: IMAGE_NAMESPACE
  description: The namespace containing the build image
  value: pdfmagic-tools
  required: true
- name: GITHUB_WEBHOOK_SECRET
  description: A secret string used to configure the GitHub webhook
  generate: expression
  from: "[a-zA-Z0-9]{40}"
  required: true
- name: GENERIC_WEBHOOK_SECRET
  description: A secret string used to configure the Generic webhook
  generate: expression
  from: "[a-zA-Z0-9]{40}"
  required: true
- name: GIT_REPOSITORY_URL
  description: repository containing flask app
  value: https://github.com/bcgov/pdfmagic
  required: true
- name: GIT_BRANCH
  description: git branch to use
  value: master
  required: true